export default {
  'WIN_RESIZE': 'WIN_RESIZE',
  'SET_HEADER_HEIGHT': 'SET_HEADER_HEIGHT',
  'SET_FOOTER_HEIGHT': 'SET_FOOTER_HEIGHT',
  'SET_LEFTER_WIDTH': 'SET_LEFTER_WIDTH',
  'SET_RIGHTER_WIDTH': 'SET_RIGHTER_WIDTH',
  'CREATE_SVG': 'CREATE_SVG',
  'SET_SVG_WIDTH': 'SET_SVG_WIDTH',
  'SET_ACTIVE_ID': 'SET_ACTIVE_ID',
  INCREMENT_MAIN_COUNTER: 'INCREMENT_MAIN_COUNTER',
  REMOVE_SVG: 'REMOVE_SVG',
  SET_ATTR_LIST: 'SET_ATTR_LIST',
  SET_CURSOR_POINT: 'SET_CURSOR_POINT'
}
