export default {
  'WIN_RESIZE': 'WIN_RESIZE',
  'SET_HEADER_HEIGHT': 'SET_HEADER_HEIGHT',
  'SET_FOOTER_HEIGHT': 'SET_FOOTER_HEIGHT',
  'SET_LEFTER_WIDTH': 'SET_LEFTER_WIDTH',
  'SET_RIGHTER_WIDTH': 'SET_RIGHTER_WIDTH'
}
